---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-run
  namespace: application
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: mlflow-run
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-run
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-run
  template:
    metadata:
      labels:
        app: mlflow-run
    spec:
      containers:
      - name: mlflow
        image: docker.io/bitnamilegacy/mlflow:3.3.2-debian-12-r0
        env:
        # Авторизація для UI та скриптів
        - name: MLFLOW_TRACKING_USERNAME
          value: "admin"
        - name: MLFLOW_TRACKING_PASSWORD
          value: "password123"
        # З'єднання з базою (динамічний пароль з секрету)
        - name: MLFLOW_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-postgresql
              key: postgresql-password
        - name: MLFLOW_DATABASE_HOST
          value: "mlflow-postgresql"
        - name: MLFLOW_DATABASE_PORT_NUMBER
          value: "5432"
        - name: MLFLOW_DATABASE_NAME
          value: "mlflow_db"
        - name: MLFLOW_DATABASE_USER
          value: "postgres"
        ports:
        - containerPort: 5000
